name: Deploy Lambda Function

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project
        run: mvn clean install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Lambda Deployment Package
        run: |
          mkdir -p build
          cp target/EmailSenderLambda-1.0-SNAPSHOT.jar build/lambda_function.jar

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:904233093704:function:SiteContactEmail \
            --zip-file fileb://build/lambda_function.jar
